AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda with nestjs.

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: oh-nest-lambda
      StageName: api
      EndpointConfiguration: REGIONAL
      Cors:
        AllowMethods: "'PUT'"
        AllowHeaders: "'X-Request-Id,Content-Type'"
        AllowOrigin: "'*'"
  ProxyFuncion:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambda-entry-point.handler
      Runtime: nodejs12.x
      CodeUri: deploy/nest-lambda.zip
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId: !Ref ApiGateway

Outputs:
  ApiGatewayId:
    Description: Api Gateway Id
    Value: !Ref ApiGateway
  ProxyFunctionArn:
    Description: Proxy Function Arn
    Value: !GetAtt ProxyFuncion.Arn